language: python
python:
- '2.7'
script:
- touch foo
deploy:
  provider: pypi
  user: jlawhead
  password:
    secure: "KVcJrlxUjtq3OzYseoNUtR+wm2rPm6m5AdUzNCwqDJKCP7s95RqUn1oq9cWA7iqvTHLjC9bExlRWGWX+ekzGNQJrH2xEddsrByFpVbZ1l6GXSt+s9E8h+mceNGjGALpcBTIQiLAZ/0435YJZmMgOovS0S9sqNRtqisGfC6uZU1Iw3atGOAOyO8/pVpp8UVm2D1/AhCDvGjPLV3S+gTIUUyFiv5V40Gcq/41fauRRHQ6nOv4N8v4bQwgiRhvXIPj5PYl0uPofrzPKPE/etYFIaIm+44fsyNWX37J5R43VSD872olsYtjzwU3PFyKbqcn+Ti3dXVZ3uNj83MHcGvoPlsmbt5hQfz2bMnAg1gWE6w9RTujR2Hd0UEZowLJLp71NPLdRr1fRckaixLLKB7WkUKZfBuFMFYogPVP0M9x2hM3i+RGX8u6N79YicOy5tvppXmzgfLumVW0D/eqB/bLSFmTEht14rqP8FTL3LOASlCIYhj1zNU1F64CaDTJPZ+ZsBdAMPREC1mHvhx5VbhFYLo1rZbju7gYXq4v5K+CYfM2kkBrKH6Dg/yq8bADEi5TwqzWIMtkww/oMf8pFSpk2ya0M4jVBFu2mHCkLmQ7AyDMb4EU4lDuIMrQjFzcepJa5NtWuFcPSNmcMVT1YqUSD6vt3QJ10Zh0XxPxjomDCuuU="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: GeospatialPython/pyshp
