language: python
python:
- '2.7'
script:
- touch foo
deploy:
  provider: pypi
  user: jlawhead
  password:
    secure: vtXfogyXwxd8k8CG5S+Mt9dEQa2tkV1oHuYzGh5KgBTs10uTOzslnhGvDsH8MFK7jTyGSDuLWi+ZykdORKNHnLqSYPs4KTaKYnOTvnqMmEbtowtzWkt1CakLYSjO3tbgreB5x9M9/Pgl6XrMuCjf0otpylgCBVzn6VyWVqt/v1b+ojoU4wR0rhQoRLiLY77h7DYCcViL4cqrnXqM7wbd0XvD0I3h/ybDkpfB4+8eqIypIWRJluGA3n9XptvD4R7Ih+VDgP5v76eJ407jWuNsPrBDlYc2Rz2R/ykt0HYYrCVP7Rfnkv+u3bxyyskB/id7GkIy104vsc3jCWA9MjUsz1P3x8lRUDw2BZlE1hYDa+Gkx85v6eufTNf0UHM4Czjed0ULSOvklBM8UXgJnqZPBjRRnktN+u5aIHg23TJ0hNUDhmtgYNko2BtfOGeyFvDthF62wK1iQs3dUL2fP8BzGDVn76bVgilWSH3Ye11Y9sCKeqJztg/3/CBWA3+0m/2KlgcFa44bRxpiT9H65NGl9irgXfP5DVFqemUCu6tbhJDF9gcxTBaEehBIc/hd5Dg7+221vrDKBlMViJgt1t7LuYX7XvHTw1arhdXRVPPBf2VSriVIJrbUJmkBmGGU4UPAjOU8TOZ5CPnuM3jnZTTnCEHfFKLrN9bzdOCiy0OU1Ec=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: GeospatialPython/pyshp
